### ISSUE TITLE
ICP理解测试

### ISSUE THREAD

**Issue by Yijia-Zhou** [Yijia-Zhou/ICPtest#5]
@bqx619

**Comment by bqx619** [comment]
@Yijia-Zhou 
开始 icp 理解测试, 开始于: 1574404112.957709
1. 如何申请成为小白健康众合社区认证贡献者?

**Comment by Yijia-Zhou** [comment]
发邮件到：job@sibbay.ai,格式:

```
题目：申请成为小白众和社区贡献者
内容：
个人简介：说明技术相关特长，并希望进行的贡献（前端、后端、产品、项目管理等等）
```

收到申请后社区会视情况安排进行icp流程认证，见[《贡献者认证流程》](贡献者认证流程.md)，在通过认证后成为认证贡献者。

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确, 

2. 小白健康的 icp, 分别代表着什么?

**Comment by Yijia-Zhou** [comment]
### issue、commit/comment、pr

---

为了实现社区的目标设计了icp操作方式

icp（issue、commit/comment、pr)机制的核心原则是：

1. issue就是一切
	凡没有在 issue 中记录的，都没有发生。

2. 提交物是目标

	一切有价值的贡献均应有对应提交物（可以是代码、设计、文档等等），并以此为衡量工作量的唯一依据；  

	说明：
	- 提交物可以是pr中内容，也可以在issue中包含并说明，只要EI的reviewer看得清楚即可

3. 评价来自社区
	issue的size是否合理由社区成员进行投票评价

**Comment by Yijia-Zhou** [comment]
@bqx619

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确, 其实就是 issue、commit/comment、pr

3. 小白健康众合社区的价值观是?

**Comment by Yijia-Zhou** [comment]
@bqx619 
- 尊重、信任；
- 愿以悲悯之心为公众的健康做贡献
- 严格的执行标准；
- 协作和为协作提供便利；
- 当你没有时间时，请告诉大家；
- 保障信息的安全；

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确, 

4. 小白健康众合社区参与者的条件是?

**Comment by Yijia-Zhou** [comment]
@bqx619 
- 个人，不得是组织、团队；
- 认同小白众和的理念和价值观；

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确,

5. 小白健康的众合核心思想是?

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确,

5. 小白健康的众合核心思想是?

**Comment by Yijia-Zhou** [comment]
@bqx619 
**以尊重和信任为基础，自主参与为形式，公正奖励为机制，以实现高效、可持续、可预期的商业目标的众人和合形式。**

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确,

6. 如何申请开发一个 issue

**Comment by Yijia-Zhou** [comment]
contributor或committer均可自由申请icp任务的开发，在icp issue的comment中提交下面的文字：  
```
申请开发 deadline:yyyy-mm-dd [size:xx] [@xxx] [文字]
```
注意点：
- 请严格按照这个格式填写，否则可能会无法计入统计；
- deadline是以引用pr merge的日期为准，所以建议留有一定余量进行review及修改；
- size可以在这确定，也可以后面单独申请；
- 一般不建议一个issue的size太大，如果本来工作量就很大那么建议拆分为多个issue；
- @给committer
- 申请开发comment提交的时间就是starttime

**Comment by Yijia-Zhou** [comment]
@bqx619 又忘了艾特了ORZ

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确

7. PR中如何引用一个issue？

**Comment by Yijia-Zhou** [comment]
@bqx619 

在pr的正文或comment中撰写如下文字：
```
fix|for:issue-url [文字]
```
每一行写一个issue

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确.

8. 有效 issue 的条件是什么?

**Comment by Yijia-Zhou** [comment]
@bqx619 

issue 在创建时 @ 给相关 committer 或者 contributor, committer 打上 icp 的 label 作为标记，贡献者按规范申请开发，committer 在确定接受 contributor 的申请后，将 assigness 指定为该 contributor，并打上size的标签，被打上 icp label 的 pr 引用且该 pr 被 merge, 则该 issue 为 有效 issue.

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确

9. issue 的 size 是否可以修改, 如何修改?

**Comment by Yijia-Zhou** [comment]
@bqx619 

如果实际工作量与预估要较大的出入，contributer 可根据实际情况向 committer 提出 size 变更：  
变更申请需写明原因和size调整的数量，并经 committer 确认。

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确

10. ti 是什么, 如何计算?

**Comment by Yijia-Zhou** [comment]
@bqx619 

### 按时指数ti
```
ti = （deadline-starttime)/(mergetime-starttime)<=1?1:(0.7*（deadline-starttime)/(mergetime-starttime))
```
说明：
- starttime是以提出申请的comment的时间为准，如果contributer认为committer的确认回复太晚会影响deadline的完成，应该马上申请修改deadline。
- mergetime表示pr被merge的时间
- deadline是指定日期的24:00
- ti的计算精度是hour

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确

11. EI 是如何计算的, SHT 奖励每个人是如何分配的?

**Comment by Yijia-Zhou** [comment]
@bqx619 

**效率指数(Efficiency Index)** 指的是 当月该贡献者的 效率分数(ES)[1] 除以 当月该贡献者的 icp size
说明：
- 每月19日00:00公布EI表在：[icp.sibbay.ai](http://icp.sibbay.ai)
- 每月17日00:00-每月19日00:00 为评价时间

[1]效率分数(Efficiency Score, ES)

	是 contributor 和 committer 的在单位size贡献效率的评估，该指标核心由所有contributer投票产生，是一个仅仅具有比较意义的指标。

	说明：

	- 由系统以本月所有的icp issue为基础，生成issue对比pair

	- 由系统将这些issue pair分配给本月的贡献者，进行比较确定其中效率更高者，则该issue获得1*size的EI点

	- 如果在规定时间内未提交评判结果，则reviewer会被扣除 1*(size1+size2) 的ES点，并公开reviewer

	- 每月19日00:00公布ES表在：[icp.sibbay.ai](http://icp.sibbay.ai)

	- 每月17日00:00-每月19日00:00 为评价时间

### 贡献奖励
#### 条件
- 本月EI>=0.8的贡献者有权利参与本月贡献奖励的分配。
#### 数量
- 每个月由社区根据任务完成和用户使用（挖矿）的情况确定token奖励的总数T；
- 每个人分配的数量：以个人CI*贡献者级别指数在本月总CI的比例乘以T
- 发放方式：50%是立即可兑现SHT、50%为一年锁定期SHT；

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确, 可以准备好自己的 token 账号了

12. 小白健康的效率条款是?

**Comment by Yijia-Zhou** [comment]
@bqx619 

- 连续第二个月EI小于0.8（不包含），则该贡献者仅发放当月size奖励的50%；
- 连续第二个月EI小于0.4（不包含），则对其主管committer处以该贡献者当月size金额的处罚；

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确

13. 违反社区价值观的后果是什么?

**Comment by Yijia-Zhou** [comment]
@bqx619 

社区要求每个贡献者均要遵循前社区的六条价值观，一旦出现一下行为：

- 坚决杜绝EI窜投行为，小白视为最恶劣之行径，一经发现以直接冻结SHT账户
- 没有时间时，未能及时告知社区
- 违反小白的版权管理规定
- 数据保密规定
- 虚报工作量
- 删除他人的issue留言
- 以及一切违反小白价值观的行为

一经证实，小白有权停止其贡献资格，并减少甚至取消其 CI 值。

**Comment by bqx619** [comment]
@Yijia-Zhou 回答正确, ICP 理解测试结束, 可以关闭 issue, 但请保留它
