### ISSUE TITLE
协作 issue

### ISSUE THREAD

**Issue by Yijia-Zhou** [Yijia-Zhou/ICPtest#6]
@bqx619

**Comment by bqx619** [comment]
@Yijia-Zhou 做一些简单的对话, 开始时间: 1574407613.1424608
第一次协作

**Comment by Yijia-Zhou** [comment]
@bqx619 

RE: 第一次协作

**Comment by bqx619** [comment]
@Yijia-Zhou 第二次协作

**Comment by Yijia-Zhou** [comment]
@bqx619 

RE: 第二次协作

**Comment by bqx619** [comment]
@Yijia-Zhou 第三次协作

**Comment by Yijia-Zhou** [comment]
@bqx619

RE: 第三次协作

**Comment by bqx619** [comment]
@Yijia-Zhou 第四次协作

**Comment by Yijia-Zhou** [comment]
@bqx619

RE: 第四次协作

**Comment by bqx619** [comment]
@Yijia-Zhou 第五次协作

**Comment by Yijia-Zhou** [comment]
@bqx619

RE: 第五次协作

**Comment by bqx619** [comment]
@Yijia-Zhou 协作结束, 协作者共耗时 908s, 折约 0.25 小时, 申请者共耗时 18 分钟, 折约 0.3 小时
